// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_DotProduct
Eigen::MatrixXd cpp_DotProduct(Rcpp::List mats);
RcppExport SEXP _repsim_cpp_DotProduct(SEXP matsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mats(matsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_DotProduct(mats));
    return rcpp_result_gen;
END_RCPP
}
// cpp_LinReg
Eigen::MatrixXd cpp_LinReg(Rcpp::List mats);
RcppExport SEXP _repsim_cpp_LinReg(SEXP matsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mats(matsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_LinReg(mats));
    return rcpp_result_gen;
END_RCPP
}
// cpp_HSIC
Eigen::MatrixXd cpp_HSIC(Rcpp::List mats, std::string type, std::string estimator);
RcppExport SEXP _repsim_cpp_HSIC(SEXP matsSEXP, SEXP typeSEXP, SEXP estimatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mats(matsSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type estimator(estimatorSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_HSIC(mats, type, estimator));
    return rcpp_result_gen;
END_RCPP
}
// cpp_CKA
Eigen::MatrixXd cpp_CKA(Rcpp::List mats, std::string type, std::string estimator);
RcppExport SEXP _repsim_cpp_CKA(SEXP matsSEXP, SEXP typeSEXP, SEXP estimatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mats(matsSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type estimator(estimatorSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_CKA(mats, type, estimator));
    return rcpp_result_gen;
END_RCPP
}
// cpp_CCA
Eigen::MatrixXd cpp_CCA(Rcpp::List mats, std::string type);
RcppExport SEXP _repsim_cpp_CCA(SEXP matsSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mats(matsSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_CCA(mats, type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_SVCCA
Eigen::MatrixXd cpp_SVCCA(Rcpp::List mats, std::string type);
RcppExport SEXP _repsim_cpp_SVCCA(SEXP matsSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mats(matsSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_SVCCA(mats, type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_PWCCA
Eigen::MatrixXd cpp_PWCCA(Rcpp::List mats);
RcppExport SEXP _repsim_cpp_PWCCA(SEXP matsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mats(matsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_PWCCA(mats));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_repsim_cpp_DotProduct", (DL_FUNC) &_repsim_cpp_DotProduct, 1},
    {"_repsim_cpp_LinReg", (DL_FUNC) &_repsim_cpp_LinReg, 1},
    {"_repsim_cpp_HSIC", (DL_FUNC) &_repsim_cpp_HSIC, 3},
    {"_repsim_cpp_CKA", (DL_FUNC) &_repsim_cpp_CKA, 3},
    {"_repsim_cpp_CCA", (DL_FUNC) &_repsim_cpp_CCA, 2},
    {"_repsim_cpp_SVCCA", (DL_FUNC) &_repsim_cpp_SVCCA, 2},
    {"_repsim_cpp_PWCCA", (DL_FUNC) &_repsim_cpp_PWCCA, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_repsim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
