# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_DotProduct <- function(mats) {
    .Call(`_repsim_cpp_DotProduct`, mats)
}

cpp_LinReg <- function(mats) {
    .Call(`_repsim_cpp_LinReg`, mats)
}

cpp_HSIC <- function(mats, type, estimator = "gretton") {
    .Call(`_repsim_cpp_HSIC`, mats, type, estimator)
}

cpp_CKA <- function(mats, type, estimator = "gretton") {
    .Call(`_repsim_cpp_CKA`, mats, type, estimator)
}

cpp_CCA <- function(mats, type) {
    .Call(`_repsim_cpp_CCA`, mats, type)
}

cpp_SVCCA <- function(mats, type) {
    .Call(`_repsim_cpp_SVCCA`, mats, type)
}

cpp_PWCCA <- function(mats) {
    .Call(`_repsim_cpp_PWCCA`, mats)
}

