// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// KernelLinear
arma::mat KernelLinear(arma::mat X);
RcppExport SEXP _repsim_KernelLinear(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(KernelLinear(X));
    return rcpp_result_gen;
END_RCPP
}
// KernelRBF
arma::mat KernelRBF(arma::mat X, bool use_auto, double bandwidth);
RcppExport SEXP _repsim_KernelRBF(SEXP XSEXP, SEXP use_autoSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type use_auto(use_autoSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(KernelRBF(X, use_auto, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// src_orthobase
arma::mat src_orthobase(arma::mat& X, bool centering);
RcppExport SEXP _repsim_src_orthobase(SEXP XSEXP, SEXP centeringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type centering(centeringSEXP);
    rcpp_result_gen = Rcpp::wrap(src_orthobase(X, centering));
    return rcpp_result_gen;
END_RCPP
}
// cpp_LR
arma::mat cpp_LR(arma::field<arma::mat>& config_list, bool centering);
RcppExport SEXP _repsim_cpp_LR(SEXP config_listSEXP, SEXP centeringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat>& >::type config_list(config_listSEXP);
    Rcpp::traits::input_parameter< bool >::type centering(centeringSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_LR(config_list, centering));
    return rcpp_result_gen;
END_RCPP
}
// cpp_DP
arma::mat cpp_DP(arma::field<arma::mat>& config_list, bool centering);
RcppExport SEXP _repsim_cpp_DP(SEXP config_listSEXP, SEXP centeringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat>& >::type config_list(config_listSEXP);
    Rcpp::traits::input_parameter< bool >::type centering(centeringSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_DP(config_list, centering));
    return rcpp_result_gen;
END_RCPP
}
// cpp_HSIC
arma::mat cpp_HSIC(arma::field<arma::mat>& config_list, std::string par_kernel, double par_sigma, bool use_auto);
RcppExport SEXP _repsim_cpp_HSIC(SEXP config_listSEXP, SEXP par_kernelSEXP, SEXP par_sigmaSEXP, SEXP use_autoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat>& >::type config_list(config_listSEXP);
    Rcpp::traits::input_parameter< std::string >::type par_kernel(par_kernelSEXP);
    Rcpp::traits::input_parameter< double >::type par_sigma(par_sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_auto(use_autoSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_HSIC(config_list, par_kernel, par_sigma, use_auto));
    return rcpp_result_gen;
END_RCPP
}
// cpp_CKA
arma::mat cpp_CKA(arma::field<arma::mat>& config_list, std::string par_kernel, double par_sigma, bool use_auto);
RcppExport SEXP _repsim_cpp_CKA(SEXP config_listSEXP, SEXP par_kernelSEXP, SEXP par_sigmaSEXP, SEXP use_autoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat>& >::type config_list(config_listSEXP);
    Rcpp::traits::input_parameter< std::string >::type par_kernel(par_kernelSEXP);
    Rcpp::traits::input_parameter< double >::type par_sigma(par_sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_auto(use_autoSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_CKA(config_list, par_kernel, par_sigma, use_auto));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_repsim_KernelLinear", (DL_FUNC) &_repsim_KernelLinear, 1},
    {"_repsim_KernelRBF", (DL_FUNC) &_repsim_KernelRBF, 3},
    {"_repsim_src_orthobase", (DL_FUNC) &_repsim_src_orthobase, 2},
    {"_repsim_cpp_LR", (DL_FUNC) &_repsim_cpp_LR, 2},
    {"_repsim_cpp_DP", (DL_FUNC) &_repsim_cpp_DP, 2},
    {"_repsim_cpp_HSIC", (DL_FUNC) &_repsim_cpp_HSIC, 4},
    {"_repsim_cpp_CKA", (DL_FUNC) &_repsim_cpp_CKA, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_repsim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
