# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KernelLinear <- function(X) {
    .Call('_repsim_KernelLinear', PACKAGE = 'repsim', X)
}

KernelRBF <- function(X, use_auto, bandwidth) {
    .Call('_repsim_KernelRBF', PACKAGE = 'repsim', X, use_auto, bandwidth)
}

src_orthobase <- function(X, centering) {
    .Call('_repsim_src_orthobase', PACKAGE = 'repsim', X, centering)
}

cpp_GSR_procrustes <- function(data3d) {
    .Call('_repsim_cpp_GSR_procrustes', PACKAGE = 'repsim', data3d)
}

cpp_GSR_kendall <- function(data3d) {
    .Call('_repsim_cpp_GSR_kendall', PACKAGE = 'repsim', data3d)
}

cpp_GSL <- function(data3d, alpha) {
    .Call('_repsim_cpp_GSL', PACKAGE = 'repsim', data3d, alpha)
}

cpp_LR <- function(config_list, centering) {
    .Call('_repsim_cpp_LR', PACKAGE = 'repsim', config_list, centering)
}

cpp_DP <- function(config_list, centering) {
    .Call('_repsim_cpp_DP', PACKAGE = 'repsim', config_list, centering)
}

cpp_HSIC <- function(config_list, par_kernel, par_sigma, use_auto) {
    .Call('_repsim_cpp_HSIC', PACKAGE = 'repsim', config_list, par_kernel, par_sigma, use_auto)
}

cpp_CKA <- function(config_list, par_kernel, par_sigma, use_auto) {
    .Call('_repsim_cpp_CKA', PACKAGE = 'repsim', config_list, par_kernel, par_sigma, use_auto)
}

